FROM fatedier/frps:v0.44.0

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk add tzdata \
&& cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& echo "Asia/Shanghai" > /etc/timezone \
&& apk del tzdata

WORKDIR /home/frp
COPY ./startup-frps.sh /home/frp/startup-frps.sh

ENV BIND_PORT="7000"

ENTRYPOINT ["sh","startup-frps.sh"]
