FROM fatedier/frps:v0.51.3

RUN apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata

WORKDIR /home/frp
COPY ./startup-frps.sh /home/frp/startup-frps.sh

ENV BIND_PORT="7000"

ENTRYPOINT ["sh","startup-frps.sh"]
