FROM fatedier/frpc:v0.53.2

RUN apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata \
    && apk add --no-cache jq \
    && apk add --no-cache bash

WORKDIR /home/frp
COPY ./startup-frpc.sh /home/frp/startup-frpc.sh

ENV SERVER_ADDR="127.0.0.1" \
    SERVER_PORT="7000"

ENTRYPOINT ["bash","startup-frpc.sh"]
