FROM fatedier/frpc:v0.44.0

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& apk add jq \
&& apk add bash \
&& echo "Asia/Shanghai" > /etc/timezone \
&& apk del tzdata


WORKDIR /home/frp
COPY ./startup-frpc.sh /home/frp/startup-frpc.sh


ENV SERVER_ADDR="127.0.0.1" \
    SERVER_PORT="7000"

# ENV CLIENTS="ssh:tcp:127.0.0.1:8080:6000"

ENTRYPOINT ["bash","startup-frpc.sh"]
